# Generated by Django 3.1.6 on 2021-02-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurdApp', '0002_auto_20210206_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
